config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'home#index'

  get '/greenhouses' => 'greenhouses#index'
  get '/hydroponics' => 'hydroponics#index'
  get '/hydroponics/show' => 'hydroponics#show'

  authenticate :user, lambda { |u| u.admin == true } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  namespace :api do
    namespace :v1 do
      resources :hydroponics_data do
        get '/last_data' => 'hydroponics_data#last_data', on: :collection
      end
      resources :hydroponics
      post '/sessions/authenticate' => 'session#authenticate'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/greenhouse.rb
class Greenhouse < ApplicationRecord
  belongs_to :user
  has_many :hydroponics
end

app/models/hydroponic.rb
class Hydroponic < ApplicationRecord
  before_create :set_access_token

  belongs_to :greenhouse
  has_many :hydroponic_datas

  private

  def set_access_token
    self.token = generate_token
  end

  def generate_token
    loop do
      token = SecureRandom.hex(10)
      break token unless Hydroponic.where(token: token).exists?
    end
  end
end

app/models/hydroponic_data.rb
class HydroponicData < ApplicationRecord
  belongs_to :hydroponic

  def self.hydroponic_param(id, param)
    where(hydroponic_id: id).collect { |p| [p.created_at.strftime('%d/%m %H:%M'), p.public_send(param)] }
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :greenhouses
end

app/controllers/api/v1/hydroponics_controller.rb
module Api
  module V1
    class HydroponicsController < ApplicationController
      def index
        render json: set_hydroponic
      end

      private

      def set_hydroponic
        Hydroponic.find_by_token(params[:token])
      end
    end
  end
end

app/controllers/api/v1/hydroponics_data_controller.rb
module Api
  module V1
    class HydroponicsDataController < ApplicationController
      skip_before_action :verify_authenticity_token, :only => [:create]

      def index
        hydroponic_data = HydroponicData.where(hydroponic_id: set_hydroponic)
        render json: hydroponic_data
      end

      def create
        @hydroponic_data = HydroponicData.new(hydroponic_data_params)
        @hydroponic_data.hydroponic_id = set_hydroponic.id

        if @hydroponic_data.save
          render json: @hydroponic_data, status: :created, location: @hydroponic_data
        else
          render json: @hydroponic_data.errors, status: :unprocessable_entity
        end
      end

      def last_data
        @hydroponic_data = HydroponicData.where(hydroponic_id: params[:hydroponic_id]).sort({ _id: -1 }).limit(1)
        render json: @hydroponic_data
      end

      private

      def set_hydroponic
        Hydroponic.find_by_token(params[:token])
      end

      def hydroponic_data_params
        params.permit(:hydroponic_id, :temperature, :humidity, :c, :ce, :waterflow)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  before_action :authenticate_user!
  layout 'authentication'
end

app/controllers/greenhouses_controller.rb
class GreenhousesController < ApplicationController
  before_action :authenticate_user!

  def index
    @title = 'Estufas'
    @greenhouses = Greenhouse.where(user: current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @title = 'Página inicial'
  end
end

app/controllers/hydroponics_controller.rb
class HydroponicsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @title = 'Bancadas'
    @hydroponics = Hydroponic.where(greenhouse_id: params[:greenhouse_id])
  end

  def show
    @title = "Bancada #{params[:hydroponic_id]}"
    @data = [
      [{ name: 'Temperatura e Umidade', data: get_param('temperature') }, { name: 'Umidade', data: get_param('humidity') }],
      [{ name: 'PH', data: get_param('ph') }],
      [{ name: 'Condutividade', data: get_param('ce') }],
      [{ name: 'Vazão', data: get_param('waterflow') }]
    ]
  end

  private

  def get_param(param)
    HydroponicData.hydroponic_param(params[:hydroponic_id], param)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/greenhouses_helper.rb
module GreenhousesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hydroponics_helper.rb
module HydroponicsHelper
end

app/views/greenhouses/index.html.erb
<div class="" style="padding-left: 1px;">
  <div class="row">
    <% @greenhouses.each do |greenhouse| %>
      <%= link_to hydroponics_path(greenhouse_id: greenhouse.id) do %>
        <div class="col hydroponic s12 m6 l3 teal darken-2">
          <span class="flow-text"><%= greenhouse.identifier %></span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<a href="#modal1" class="modal-trigger btn-floating btn-large waves-effect teal darken-2 fixed-button">
  <i class="material-icons">add</i>
</a>


<div id="modal1" class="modal">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <p>A bunch of text</p>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
  </div>
</div>

app/views/hydroponics/index.html.erb
<div class="" style="padding-left: 1px;">
  <div class="row">
    <% @hydroponics.each do |hydroponic| %>
      <%= link_to hydroponics_show_path(greenhouse_id: params[:greenhouse_id], hydroponic_id: hydroponic.id) do %>
        <div class="col hydroponic s12 m6 l3 teal darken-2">
          <span class="flow-text"><%= hydroponic.identifier %></span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<a href="#modal1" class="modal-trigger btn-floating btn-large waves-effect teal darken-2 fixed-button">
  <i class="material-icons">add</i>
</a>

<div id="modal1" class="modal">
  <div class="modal-content">
    <h4>Modal Header</h4>
    <p>A bunch of text</p>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
  </div>
</div>

app/views/hydroponics/show.erb
<div class="" style="padding-left: 1px;">
  <div class="row">
    <% @data.each do |data| %>
      <div class="col hydroponic s12 m6 l6 white container_data">
        <h5><%= data.first[:name] %></h5>   
        <%= line_chart data %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
	<%
		unless ['success', 'danger', 'error'].include?(key)
			key = 'notice'
		end
	%>
  <div id="alert" class="alert-message alert-message-<%= key %>">
    <%= value.to_s.html_safe %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PcdhApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <nav>
      <div class="nav-wrapper grey darken-3">
        <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <a href="#" class="brand-logo" style="padding-left: 20px;"><%= @title %></a>
      </div>
    </nav>
    <ul id="slide-out" class="sidenav sidenav-fixed grey lighten-4">
      <li>
        <div class="user-view">
          <a href="#user"><img class="circle" src='<%= current_user.avatar %>'/></a>
          <span class="name"><%= current_user.name %></span>
          <span class="email"><%= current_user.email %></span>
        </div>
      </li>
      <li><div class="divider"></div></li>
      <li><a href="/"><i class="material-icons">insert_chart</i>Página Inicial</a></li>
      <!-- <li><div class="divider"></div></li> -->
      <li><a href="/greenhouses"><i class="material-icons">insert_chart</i>Estufa</a></li>
      <!-- <li><div class="divider"></div></li> -->
      <li><a href="#"><i class="material-icons">description</i>Micro-Clima</a></li>
      <!-- <li><div class="divider"></div></li> -->
      <li>
      <%= link_to destroy_user_session_path, :method => :delete do %>
        <i class="material-icons">date_range</i>Sair
      <% end %>
      </li>
      <!-- <li><div class="divider"></div></li> -->
    </ul>
    <main>
      <%= render "layouts/alerts" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PcdhApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'authentication', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>